import type { ExampleConfig } from '../index.ts'
import { MULTI_INDUSTRIES, MULTI_TITLES, MULTI_TOPICS } from '../pools.ts'

const base = {
  theme: 'multi' as const,
  industryPool: MULTI_INDUSTRIES,
  titlePool: MULTI_TITLES,
  sessionTopics: MULTI_TOPICS,
}

export const multiExamples: ExampleConfig[] = [
  { ...base, id: 'global-business-expo-2026', order: 15, eventName: 'Global Business Expo 2026', tagline: 'Cross-industry deals under one roof', venue: 'Dubai World Trade Centre', city: 'Dubai', country: 'United Arab Emirates', dates: { start: '2026-11-16', end: '2026-11-18' }, seed: 301, difficulty: 'hard', layout: 'paginated-list', surface: 'api-spa', label: 'Multi · hard · API-SPA (JSON only) · 1200c · full fields · obfuscated emails', scale: { individuals: 0, companies: 1200, sessions: 0 }, coverage: { entities: ['companies'], emailsInline: false, fieldFullness: 'full' } },
  { ...base, id: 'manufacturing-week-2026', order: 16, eventName: 'Manufacturing Week 2026', tagline: 'Automation and the modern factory floor', venue: 'NEC Birmingham', city: 'Birmingham', country: 'United Kingdom', dates: { start: '2026-09-29', end: '2026-10-01' }, seed: 302, difficulty: 'medium', layout: 'card-grid', surface: 'ssr', label: 'Multi · medium · SSR · 400p/200c · full fields', scale: { individuals: 400, companies: 200, sessions: 30 }, coverage: { entities: ['individuals', 'companies', 'events'], emailsInline: true, fieldFullness: 'full' } },
  { ...base, id: 'retailnxt-2026', order: 17, eventName: 'RetailNXT 2026', tagline: 'Omnichannel retail, reimagined', venue: 'Javits Center', city: 'New York', country: 'United States', dates: { start: '2026-01-27', end: '2026-01-28' }, seed: 303, difficulty: 'easy', layout: 'single-roster', surface: 'ssr', label: 'Multi · easy · SSR · 300p · full fields', scale: { individuals: 300, companies: 0, sessions: 0 }, coverage: { entities: ['individuals'], emailsInline: true, fieldFullness: 'full' } },
  { ...base, id: 'energy-forum-2026', order: 18, eventName: 'Energy Forum 2026', tagline: 'Powering the transition to clean energy', venue: 'Messe Frankfurt', city: 'Frankfurt', country: 'Germany', dates: { start: '2026-05-19', end: '2026-05-21' }, seed: 304, difficulty: 'hard', layout: 'dense-table', surface: 'api-hybrid', label: 'Multi · hard · API-hybrid · 700p/350c · full fields · obfuscated emails', scale: { individuals: 700, companies: 350, sessions: 30 }, coverage: { entities: ['individuals', 'companies', 'events'], emailsInline: false, fieldFullness: 'full' } },
  { ...base, id: 'logistics-live-2026', order: 19, eventName: 'Logistics Live 2026', tagline: 'Resilient supply chains for a volatile world', venue: 'Kentucky Exposition Center', city: 'Louisville', country: 'United States', dates: { start: '2026-03-24', end: '2026-03-26' }, seed: 305, difficulty: 'medium', layout: 'card-grid', surface: 'ssr', label: 'Multi · medium · SSR · 500c · full fields', scale: { individuals: 0, companies: 500, sessions: 0 }, coverage: { entities: ['companies'], emailsInline: false, fieldFullness: 'full' } },
  { ...base, id: 'founders-fair-2026', order: 20, eventName: 'Founders Fair 2026', tagline: 'Early-stage builders across every industry', venue: 'Palais des Congrès', city: 'Paris', country: 'France', dates: { start: '2026-07-08', end: '2026-07-09' }, seed: 306, difficulty: 'easy', layout: 'tabbed-profiles', surface: 'ssr', label: 'Multi · easy · SSR · 150p · full fields', scale: { individuals: 150, companies: 0, sessions: 0 }, coverage: { entities: ['individuals'], emailsInline: true, fieldFullness: 'full' } },
  { ...base, id: 'enterprise-summit-2026', order: 21, eventName: 'Enterprise Summit 2026', tagline: 'Where every industry meets enterprise scale', venue: 'Orange County Convention Center', city: 'Orlando', country: 'United States', dates: { start: '2026-10-13', end: '2026-10-15' }, seed: 307, difficulty: 'hard', layout: 'infinite-scroll', surface: 'load-more', label: 'Multi · hard · Load-more (API paged) · 1000p/400c · partial fields · obfuscated emails', scale: { individuals: 1000, companies: 400, sessions: 30 }, coverage: { entities: ['individuals', 'companies', 'events'], emailsInline: true, fieldFullness: 'partial' } },
]
